### ISSUE TITLE
[Question] How do i get or set from the store in rust?

### ISSUE THREAD

**Issue by sbeckeriv** [tauri-apps/tauri-plugin-store#86]
Dearest Maintainer, 

I would like to use this store for configuration. The app I am creating has a UI and CLI. I am unsure how I can access the config from rust right now. Any advice would be appreciated.

Thanks for you work on this.
Becker

**Comment by FabianLars** [comment]
plugins generally don't have a rust api (mainly because we couldn't think of a nice design yet), but this plugin uses a plain json file at `app_dir() / store-name` or if you can't use tauri's app_dir api: `config_dir() / bundle-id / store-name`. (config_dir is part of tauri's api and [dirs-next](https://crates.io/crates/dirs-next))

Nothing special about the file itself so you can parse it yourself with [serde_json](https://crates.io/crates/serde_json).

**Comment by sbeckeriv** [comment]
Hello @FabianLars ,

Thank you for your response. I thought that this might be the case. i have seen a few plugins that lack a rust facing interface and I have been confused by this choice.  I was hoping that plugins would offer the same interface to both layers making it easier to code between the two. I misunderstood that this was a built in concept to tauri.  

You give an example but even just providing the loaded data to rust would be a simple start. There are many advantages to having the plugin provide both interfaces. Reading the set/get/clear code I can understand why it is not a simple task. 

I might take a stab at it. If there was an interface trait that a Javascript and Rust store implemented it could be bpassed around by the trait where required. The builder can build for either or.  Maybe the trait logic just handles things like `window.emit(` and is a no op for rust. 

thanks for the reply
Becker

**Comment by FabianLars** [comment]
> i have seen a few plugins that lack a rust facing interface

It's _every_ plugin. 😅 Because of 2 reasons:
1) As i mentioned earlier, we couldn't really think of a one-fits-all approach (that is actually integrated with the plugin system)
2) The main purpose of (community) plugins (not the plugin _system_ itself) is to extend the javascript api with stuff that's either only possible in rust or _should_ be done in rust. From experience most users were/are better off with a completely custom solution once they need/want to do stuff in rust anyway.
